Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,12 +1,18 @@
-name: Build Docker image of node js app
+name: Build Docker Image
 
+# This workflow will be triggered manually
 on:
-  push:
-    branches:
-      - main
-  pull_request:
-    branches:
-      - main
+  workflow_dispatch:
+    inputs:
+      app:
+        description: 'Select the application to build'
+        required: true
+        default: 'nodejs'
+        type: choice
+        options:
+          - python
+          - java
+          - nodejs
 
 jobs:
   build:
@@ -20,12 +26,24 @@ jobs:
       uses: docker/setup-buildx-action@v2
 
     - name: Build Docker image
-      uses: docker/build-push-action@v5
-      with:
-        context: ./my_node_app
-        load: true
-        tags: nodejs-app:latest
+      run: |
+        case "${{ github.event.inputs.app }}" in
+          python)
+            docker build -t python-app:latest ./python-app
+            ;;
+          java)
+            docker build -t java-app:latest ./java-app
+            ;;
+          nodejs)
+            docker build -t nodejs-app:latest ./my_node_app
+            ;;
+          *)
+            echo "Invalid application selected"
+            exit 1
+            ;;
+        esac
 
     - name: Verify Docker image
       run: |
-        docker images nodejs-app:latest
+        docker images ${{ github.event.inputs.app }}-app:latest
+
